export const W=1000,H=520;
export const defaults={sound:false,wind:false,rounds:5,sky:'night'};
export function terrain(seed=0){return Array.from({length:W+1},(_,x)=>Math.round(365+Math.sin(x/(85+seed*5)+seed)*48+Math.sin(x/190+seed*2)*48));}
export function createMatch(names=['Player 1','Player 2'],types=['rover','heavy'],options={}){return {options:{...defaults,...options},players:names.map((name,i)=>({name,type:types[i],score:0,wins:0,level:0,misses:0,angle:45,power:58,x:i?860:140})),round:0,turn:0,phase:'aim',shot:null,trail:[],result:null};}
export function startRound(m,seed=m.round%10,wind=Math.random()*30-15){m.round++;m.land=terrain(seed);m.wind=m.options.wind?wind:0;m.turn=(m.round-1)%2;m.phase='aim';m.shot=null;m.trail=[];m.result=null;m.players.forEach((p,i)=>{p.x=i?860:140;p.misses=0;p.alive=true;});}
export const tankY=(m,p)=>m.land[Math.round(p.x)]-10;
export function move(m,dx){if(m.phase!=='aim')return;let p=m.players[m.turn];p.x=Math.max(35,Math.min(965,p.x+dx));if(Math.abs(p.x-m.players[1-m.turn].x)<55)p.x-=dx;}
export function fire(m){if(m.phase!=='aim')return false;let p=m.players[m.turn],a=p.angle*Math.PI/180,dir=m.turn?-1:1,speed=p.power*6;m.shot={x:p.x+Math.cos(a)*24*dir,y:tankY(m,p)-Math.sin(a)*24-8,vx:Math.cos(a)*speed*dir,vy:-Math.sin(a)*speed,time:0};m.trail=[];m.phase='flight';return true;}
export function award(m,winner){let p=m.players[winner],old=p.level,points=Math.max(0,1600-p.misses);p.score+=points;p.wins++;p.level=Math.floor(p.score/1500);m.result={winner,points,levelUp:p.level>old};m.phase='result';}
export function impact(m,x,y){let shooter=m.players[m.turn],radius=30+shooter.level*7;let dead=m.players.map(p=>Math.hypot(p.x-x,tankY(m,p)-y)<radius+15);for(let i=Math.max(0,Math.floor(x-radius));i<=Math.min(W,Math.ceil(x+radius));i++){let depth=Math.sqrt(Math.max(0,radius*radius-(i-x)**2));m.land[i]=Math.min(H-12,Math.max(m.land[i],y+depth));}m.blast={x,y,radius};m.shot=null;if(dead[0]||dead[1]){let winner=dead[0]&&dead[1]?1-m.turn:dead[0]?1:0;award(m,winner);}else{shooter.misses++;m.turn=1-m.turn;m.phase='handoff';}return dead;}
export function step(m,dt=1/120){if(m.phase!=='flight')return;let s=m.shot;s.time+=dt;s.vx+=m.wind*dt;s.vy+=150*dt;s.x+=s.vx*dt;s.y+=s.vy*dt;m.trail.push([s.x,s.y]);if(m.trail.length>600)m.trail.shift();if(s.x<0||s.x>W||s.time>20){m.players[m.turn].misses++;m.shot=null;m.turn=1-m.turn;m.phase='handoff';return 'miss';}let hit=m.players.some(p=>Math.hypot(p.x-s.x,tankY(m,p)-s.y)<17);if(hit||s.y>=m.land[Math.round(s.x)]){impact(m,s.x,s.y);return 'impact';}}
